import { NextResponse } from "next/server";
import { cookies } from "next/headers";
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

function projectRefFromUrl(url: string) {
  const m = url.match(/^https?:\/\/([a-z0-9-]+)\.supabase\.co/i);
  return m?.[1] || null;
}

async function supabaseFromCookies() {
  const jar = await cookies();
  const ref = projectRefFromUrl(SUPABASE_URL);
  const accessToken =
    jar.get("sb-access-token")?.value ||
    (ref ? jar.get(`sb-${ref}-auth-token`)?.value : undefined) ||
    "";
  return createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
    auth: { persistSession: false },
    global: accessToken ? { headers: { Authorization: `Bearer ${accessToken}` } } : {},
  });
}

// GET /api/jobs/:id  -> return the row
export async function GET(_req: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const supabase = await supabaseFromCookies();

  const { data: ures } = await supabase.auth.getUser();
  if (!ures?.user) return NextResponse.json({ error: "Not authenticated" }, { status: 401 });

  const { data, error } = await supabase.from("jobs").select("*").eq("id", id).maybeSingle();
  if (error) return NextResponse.json({ error: error.message }, { status: 400 });
  if (!data) return NextResponse.json({ error: "Not found" }, { status: 404 });

  return NextResponse.json(data);
}

// POST /api/jobs/:id  -> “process” now (demo: mark done + write result_text)
export async function POST(_req: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const supabase = await supabaseFromCookies();

  const { data: ures } = await supabase.auth.getUser();
  if (!ures?.user) return NextResponse.json({ error: "Not authenticated" }, { status: 401 });

  // Read the current row to personalize output
  const { data: row, error: readErr } = await supabase.from("jobs").select("*").eq("id", id).maybeSingle();
  if (readErr || !row) return NextResponse.json({ error: readErr?.message || "Not found" }, { status: 404 });

  // 1) set processing
  const { error: e1 } = await supabase.from("jobs")
    .update({ status: "processing" })
    .eq("id", id);
  if (e1) return NextResponse.json({ error: e1.message }, { status: 400 });

  // 2) “Do the work” (demo output)
  const resultText = [
    `Job: ${row.title || "Untitled"}`,
    "",
    "This is a demo result generated by the processor.",
    "Replace this block with your real generation output.",
    "",
    row.prompt ? `Prompt:\n${row.prompt}` : ""
  ].join("\n");

  // 3) mark done + save result
  const { error: e2 } = await supabase.from("jobs")
    .update({ status: "done", result_text: resultText })
    .eq("id", id);
  if (e2) return NextResponse.json({ error: e2.message }, { status: 400 });

  return NextResponse.json({ ok: true });
}
